### [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np

print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### <font color=#0000FF>Ans: np.zeros產生數字為0的array, np.empty產生數字接近0的array, 若只是要初始化, 後續會改寫資料內容可以使用np.empty</font>

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
a = np.random.rand(2, 3)*100

print(a)
print(np.round(a))

[[ 8.7376762  88.04591174 61.92918198]
 [39.39469656 73.44488567 45.51392714]]
[[ 9. 88. 62.]
 [39. 73. 46.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [3]:
m = 20
n = 40

a = np.random.rand(2, 3)*(n-m)+m
print(a)
print(np.round(a))

[[24.30862027 31.48233055 31.6985426 ]
 [33.58153562 20.36257623 20.05961168]]
[[24. 31. 32.]
 [34. 20. 20.]]
