### [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
import numpy as np

a = np.arange(11)+1
print(a)

a[(a>=3) & (a<=6)] *= -1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [2]:
c = np.random.rand(3, 6)

print(c)
print(len(c[c>0.5]))

[[0.22433827 0.63472753 0.12638428 0.56819576 0.82283104 0.18688607]
 [0.87023475 0.28343775 0.90740414 0.85503506 0.80496932 0.29422759]
 [0.7845817  0.26094986 0.86924943 0.99392404 0.15330041 0.40943235]]
10
