## [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np

a = np.random.randint(10, size=6)
print("list(a): ", list(a))
print("a.tolist(): ", a.tolist())

b = a.reshape(3,2)
print("list(b): ", list(b))
print("b.tolist(): ", b.tolist())

list(a):  [3, 7, 4, 8, 0, 7]
a.tolist():  [3, 7, 4, 8, 0, 7]
list(b):  [array([3, 7]), array([4, 8]), array([0, 7])]
b.tolist():  [[3, 7], [4, 8], [0, 7]]


### <font color=#0000FF>Ans: list(a)只會把第一層的元素轉換成List，多層的話也只有第一層會轉成List，而tolist()才能達成多層的型態轉換</font>

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [2]:
a = np.random.randint(10, size=6) 

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[8 6 6 7 3 1]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [3]:
b = np.random.randint(10, size=(3,4)) 

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[3 2 2 8]
 [1 4 3 1]
 [5 3 1 9]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [4]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[7 1]
  [7 5]
  [6 8]]

 [[0 9]
  [1 9]
  [1 2]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list() 實現 a.tolist() 的效果？試著用程式實作。

In [5]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[2, 5, 9, 7, 1, 7]
[2, 5, 9, 7, 1, 7]


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[1, 1, 9, 2], [8, 9, 3, 8], [9, 6, 7, 8]]
[array([1, 1, 9, 2]), array([8, 9, 3, 8]), array([9, 6, 7, 8])]


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[9, 4], [6, 0], [9, 5]], [[7, 3], [5, 6], [2, 8]]]
[array([[9, 4],
       [6, 0],
       [9, 5]]), array([[7, 3],
       [5, 6],
       [2, 8]])]


In [8]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for i in iterable:
        newlist.append(tolist(i))
    return newlist

print(tolist(a))
print(tolist(b))
print(tolist(c))

[2, 5, 9, 7, 1, 7]
[[1, 1, 9, 2], [8, 9, 3, 8], [9, 6, 7, 8]]
[[[9, 4], [6, 0], [9, 5]], [[7, 3], [5, 6], [2, 8]]]
