### [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

### <font color=#0000FF>Ans: sum(a)是Python的內建函數, 所有型態都可使用, 另外兩種是array的函數</font>

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
import numpy as np

A = np.random.random((5, 5))
print(A)

[[0.44509035 0.78837749 0.58613531 0.87835172 0.37447693]
 [0.20245654 0.66760777 0.9850418  0.78885866 0.17398747]
 [0.22853008 0.19144664 0.61017311 0.95626084 0.08981437]
 [0.75620887 0.07275961 0.2962086  0.64838922 0.437441  ]
 [0.59205399 0.9342729  0.16073145 0.46954794 0.36899151]]


In [2]:
A = (A - A.min()) / (A.max() - A.min())
print(A)

[[0.40813111 0.78442602 0.56273784 0.88305146 0.33072806]
 [0.14216755 0.65204403 1.         0.78495345 0.11096113]
 [0.17074812 0.13009903 0.58908691 0.96845169 0.01869461]
 [0.74916432 0.         0.24493407 0.63097758 0.39974625]
 [0.56922561 0.94434957 0.09643051 0.43494035 0.3247152 ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [3]:
B = np.random.random(10)
print(B)
B[B.argmax()] = -1
print(B)

[0.08899279 0.4297903  0.76646633 0.54873424 0.80810468 0.33068891
 0.32588739 0.85213075 0.61559101 0.12028969]
[ 0.08899279  0.4297903   0.76646633  0.54873424  0.80810468  0.33068891
  0.32588739 -1.          0.61559101  0.12028969]
